# Generated by Django 2.2.2 on 2020-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanmodel',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='humanmodel',
            name='avatar',
            field=models.ImageField(upload_to='humans_avatars', verbose_name='avatar'),
        ),
    ]
