# Generated by Django 2.2.2 on 2020-04-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanapp', '0002_auto_20200420_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanmodel',
            name='avatar',
        ),
    ]
