# Generated by Django 2.2.2 on 2020-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanapp', '0003_remove_humanmodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanmodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='humans_avatars', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='humanmodel',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
