# Generated by Django 2.2.2 on 2020-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanapp', '0004_auto_20200420_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanmodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/humans_avatars', verbose_name='avatar'),
        ),
    ]
